### ISSUE TITLE
Error importing on Mac

### ISSUE THREAD

**Issue by marianoo-andres** [dynamsoft-dbr/python#1]
Hi. 

I'm trying to test this but have trouble importing dbr. I followed the instructions on the README but I'm getting the following error when calling import dbr

`dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dbr.cpython-37m-darwin.so, 2): Symbol not found: _DBR_CreateInstance
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dbr.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dbr.cpython-37m-darwin.so`

Any help would be really appreciated
Thanks.

**Comment by yushulx** [comment]
I got the following error when using Python 3:

```
clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Dev
eloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk build/temp.macosx-10.1
3-x86_64-3.7/dbr.o -L -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/s
qlite/lib -lDynamsoftBarcodeReader -o build/lib.macosx-10.13-x86_64-3.7/dbr.cpython-37
m-darwin.so
ld: warning: directory not found for option '-L-L/usr/local/lib'
ld: library not found for -lDynamsoftBarcodeReader
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

I've updated `setup.py`.
![capture](https://user-images.githubusercontent.com/2202306/46848372-026e7680-ce1c-11e8-9979-cd3a0ef62b11.PNG)

Please pull the update and try it again. Thanks.

**Comment by yushulx** [comment]
@marianoo-andres don't forget to copy the shared library to `/usr/lib`.

**Comment by marianoo-andres** [comment]
Thanks for the quick reply!

I pulled the update and tried to install again with setup.py and it crashes. 

Calling:
`sudo python3 setup.py build install`

Throws:
`/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include/numpy
running build
running build_ext
building 'dbr' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.7
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include/numpy -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c dbr.c -o build/temp.macosx-10.9-x86_64-3.7/dbr.o
In file included from dbr.c:3:
In file included from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: 
      "Using deprecated NumPy API, disable it by "          "#defining
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
dbr.c:119:15: warning: unused variable 'result' [-Wunused-variable]
    PyObject* result = NULL;
              ^
dbr.c:160:39: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
        PublicParameterSettings pSettings = {0};
                                             ^
                                             {}
dbr.c:198:39: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
        PublicParameterSettings pSettings = {0};
                                             ^
                                             {}
dbr.c:211:16: warning: incompatible integer to pointer conversion returning
      'int' from a function with result type 'PyObject *'
      (aka 'struct _object *') [-Wint-conversion]
        return -1;
               ^~
dbr.c:253:42: warning: passing 'char *' to parameter of type 'unsigned char *'
      converts between pointers to integer types with different sign
      [-Wpointer-sign]
    int ret = DBR_DecodeBuffer(hBarcode, buffer, width, height, iStride...
                                         ^~~~~~
./DynamsoftBarcodeReader.h:1170:64: note: passing argument to parameter
      'pBufferBytes' here
        DBR_API int  DBR_DecodeBuffer(void*  hBarcode, unsigned char* pBufferByt...
                                                                      ^
dbr.c:23:1: warning: unused function 'error_out' [-Wunused-function]
error_out(PyObject *m) {
^
7 warnings generated.
creating build/lib.macosx-10.9-x86_64-3.7
gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.7/dbr.o -L/usr/lib -lDynamsoftBarcodeReader -o build/lib.macosx-10.9-x86_64-3.7/dbr.cpython-37m-darwin.so
ld: library not found for -lDynamsoftBarcodeReader
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'gcc' failed with exit status 1`

**Comment by yushulx** [comment]
The problem is 

```
library not found for -lDynamsoftBarcodeReader clang: error: linker command failed with exit code 1 (use -v to see invocation) error: command 'gcc' failed with exit status 1
```

Have you downloaded the barcode library **libDynamsoftBarcodeReader.dylib** from [Dynamsoft website](https://www.dynamsoft.com/Downloads/Dynamic-Barcode-Reader-Download.aspx)?

You need to manually copy the library file to `/user/lib/`.

**Comment by marianoo-andres** [comment]
Yes. I also manually copied it to /usr/lib

There it is
![screen shot 2018-10-12 at 02 05 45](https://user-images.githubusercontent.com/22652007/46849017-86484480-cdc3-11e8-894c-8954375b6670.png)

**Comment by yushulx** [comment]
It's weird. I can't reproduce the issue. Everything is fine in my environment.
![capture](https://user-images.githubusercontent.com/2202306/46849201-f1743400-ce20-11e8-9135-ebc1df50af03.PNG)

Have you tried Python 2? Same issue?

**Comment by marianoo-andres** [comment]
Ok so I first did:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib
`

Then tried both setup with python 2 and 3 again but no luck.

Same error with python 2:
![screen shot 2018-10-12 at 02 40 12](https://user-images.githubusercontent.com/22652007/46850005-6e26f400-cdc8-11e8-9195-fafd1479d12a.png)

I don't know if it helps but first I couldn't move **libDynamsoftBarcodeReader.dylib** to **/usr/lib** because of Mac System Integrity Protection (SIP). After disabling it I was able to move it. But I don't see why it doesn't find the library.

**Comment by yushulx** [comment]
@marianoo-andres I just realized you are using **macOS 10.14 Mojave**. I'm still using 10.13.6. If you don't have access to `/usr/lib`, try to copy the library to `/usr/local/lib` and set the `LD_LIBRARY_PATH` as follows:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```

**Comment by marianoo-andres** [comment]
Great. That did the job.

Thanks!
